const images = {
    1: require('../../assets/images/backgrounds/1.jpg'),
    2: require('../../assets/images/backgrounds/2.jpg'),
    3: require('../../assets/images/backgrounds/3.jpg'),
    4: require('../../assets/images/backgrounds/4.jpg'),
    5: require('../../assets/images/backgrounds/5.jpg'),
    6: require('../../assets/images/backgrounds/6.jpg'),
    7: require('../../assets/images/backgrounds/7.jpg'),
    8: require('../../assets/images/backgrounds/8.jpg'),
    9: require('../../assets/images/backgrounds/9.jpg'),
    10: require('../../assets/images/backgrounds/10.jpg'),
    11: require('../../assets/images/backgrounds/11.jpg'),
    12: require('../../assets/images/backgrounds/12.jpg'),
    13: require('../../assets/images/backgrounds/13.jpg'),
    14: require('../../assets/images/backgrounds/14.jpg'),
    15: require('../../assets/images/backgrounds/15.jpg'),
    16: require('../../assets/images/backgrounds/16.jpg'),
    17: require('../../assets/images/backgrounds/17.jpg'),
    18: require('../../assets/images/backgrounds/18.jpg'),
    19: require('../../assets/images/backgrounds/19.jpg'),
    20: require('../../assets/images/backgrounds/20.jpg'),
    21: require('../../assets/images/backgrounds/21.jpg'),
    22: require('../../assets/images/backgrounds/22.jpg'),
    23: require('../../assets/images/backgrounds/23.jpg'),
    24: require('../../assets/images/backgrounds/24.jpg'),
};

export default images;